name:                dirtree
version:             0.1.3
synopsis:            A small library for working with directories.
description:         A small library for loading and building directories as trees.
github:              kalhauge/dirtree
author:              Christian Gram Kalhauge
maintainer:          christian@kalhauge.dk
copyright:           MIT
category:            System
extra-source-files:
- README.md
    
ghc-options:
  - -Wall

dependencies:
  - base >= 4.10 && < 5
  - directory
  - containers
  - deepseq
  - filepath
  - lens
  - zip-archive
  - bytestring
  - unix

library:
    source-dirs: src

tests:
  dirtree-test:
    source-dirs:      test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dirtree
    - hspec-discover
    - hspec
    - hspec-expectations-pretty-diff
    main:             Main.hs
