name:                dirtree
version:             0.0.1
synopsis:            A small library for working with directories.
description:         A small library for loading and building directories as trees.
homepage:            https://github.com/kalhauge/dirtree#readme
author:              Christian Gram Kalhauge
maintainer:          christian@kalhauge.dk
copyright:           MIT
category:            System
extra-source-files:
- README.md
    
ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - directory
  - containers
  - deepseq
  - filepath
  - lens

library:
    source-dirs: src

tests:
  dirtree-test:
    source-dirs:      test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dirtree
    - hspec-discover
    - hspec
    - hspec-expectations-pretty-diff
    main:             Main.hs
