name:                dirtree
version:             0.0.1
#synopsis:
#description:
homepage:            https://github.com/kalhauge/dirtree#readme
license:             BSD3
author:              Christian Gram Kalhauge
maintainer:          kalhauge@cs.ucla.edu
copyright:           MIT
category:            Web
extra-source-files:
- README.md
    
ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - directory
  - containers
  - deepseq
  - filepath
  - lens

library:
    source-dirs: src

tests:
  dirtree-test:
    source-dirs:      test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dirtree
    - hspec-discover
    - hspec
    - hspec-expectations-pretty-diff
    main:             Main.hs
